sudo: required
dist: trusty
language: cpp

matrix:
  include:

    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-5
            - unrar
            - p7zip-full
            - par2
      env:
        - COMPILER=g++-5

    - compiler: gcc
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
          packages:
            - g++-4.9
            - unrar
            - p7zip-full
            - par2
      env:
        - COMPILER=g++-4.9

    - compiler: gcc
      addons:
        apt:
          packages:
            - unrar
            - p7zip-full
            - par2
      env:
        - COMPILER=g++-4.8
        - CXXFLAGS="-std=c++11 -O2 -s"
        - CONFIGUREOPTS="--disable-cpp-check"

    - compiler: clang
      addons:
        apt:
          sources:
            - ubuntu-toolchain-r-test
            - llvm-toolchain-precise-3.6
          packages:
            - clang-3.6
            - unrar
            - p7zip-full
            - par2
      env:
        - COMPILER=clang++-3.6

install:
  - sudo pip install -U pytest

script:
  - $COMPILER --version
  - CXX=$COMPILER ./configure $CONFIGUREOPTS --enable-tests && make
  - ./nzbget --tests
  - cd tests/functional && pytest -v
